In [1]:
import pandas as pd
import numpy as np
from scipy import stats

In [2]:
sample=[1.13, 1.55, 1.43, 0.92, 1.25, 1.36, 1.32, 0.85, 1.07, 1.48, 1.20, 1.33, 1.18, 1.22, 1.29]

In [3]:
#creating dataframe

In [4]:
df=pd.DataFrame(sample)

In [5]:
df

0
0   1.13
1   1.55
2   1.43
3   0.92
4   1.25
5   1.36
6   1.32
7   0.85
8   1.07
9   1.48
10  1.20
11  1.33
12  1.18
13  1.22
14  1.29

In [6]:
df.shape

(15, 1)

In [7]:
#standard deviation of dataframe

In [8]:
std=df.std()

In [9]:
std

0    0.193164
dtype: float64

In [10]:
#mean of dataframe

In [11]:
mean=df.mean()

In [12]:
mean

0    1.238667
dtype: float64

In [13]:
#confidence interval(99%) by using normal distribution

In [14]:
df_confidence_normal=stats.norm.interval(0.99,loc=mean,scale=std)

In [15]:
print(np.round(df_confidence_normal,4))

[[0.7411]
 [1.7362]]


In [16]:
# confidence interval(%99) by using t-distribution

In [17]:
df_confidence_t=stats.t.interval(0.99,14,loc=mean,scale=std)

In [18]:
print(np.round(df_confidence_t,4))

[[0.6636]
 [1.8137]]


In [19]:
# confidence interval when population Standard deviation is known.

In [20]:
df_confidence_normal_pol=stats.norm.interval(0.99,loc=mean,scale=0.2)

In [21]:
print(np.round(df_confidence_normal_pol,4))

[[0.7235]
 [1.7538]]
